version: "3"
services:
  app:
    build:
      context: .
    container_name: citra
    restart: unless-stopped
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:8080
    volumes:
      - ./www:/var/www
  db:
    image: postgres:9-alpine
    container_name: citradb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./opt:/opt
